# Generated by Django 5.2.6 on 2025-09-07 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Ethiopian phone number (09XXXXXXXX, +2519XXXXXXXX, or 2519XXXXXXXX).', regex='^(\\+2519\\d{8}|09\\d{8}|2519\\d{8})$')]),
        ),
    ]
